{
  lib,
  pkgs,
  config,
  inputs,
  ...
}: let
  stylixEnabled = (builtins.hasAttr "stylix" config) && config.stylix.enable;
in {
  imports = [
    inputs.dms.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms-plugin-registry.modules.default
  ];

  stylix.targets.dank-material-shell.enable = lib.mkIf stylixEnabled false;

  xdg.configFile."DankMaterialShell/themes/stylix.json" = lib.mkIf stylixEnabled {
    source = with config.lib.stylix.colors.withHashtag;
      pkgs.writers.writeJSON "custom-theme.json" {
        "name" = "Stylix";
        "primary" = base0C;
        "primaryText" = base00;
        "primaryContainer" = base0D;
        "secondary" = base0E;
        "surface" = base00;
        "surfaceText" = base05;
        "surfaceVariant" = base01;
        "surfaceVariantText" = base04;
        "surfaceTint" = base0C;
        "background" = base00;
        "backgroundText" = base07;
        "outline" = base03;
        "surfaceContainer" = base01;
        "surfaceContainerHigh" = base02;
        "error" = base08;
        "warning" = base0A;
        "info" = base0D;
      };
  };

  programs.dank-material-shell = {
    enable = true;
    systemd.enable = true;

    enableVPN = true; # VPN management widget
    enableCalendarEvents = true; # Calendar integration (khal)
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableSystemMonitoring = true; # System monitoring widgets (dgop)

    plugins = {
      emojiLauncher.enable = true;
      dockerManager.enable = true;
      screenshotToggle.enable = true;
      linuxWallpaperEngine.enable = true;
    };

    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.

      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        "binds"
        "alttab"
        "wpblur"
        "colors"
        "layout"
        "outputs"
        "windowrules"
      ];
    };
  };

  systemd.user.targets.dms-session = {
    Unit = {
      Description = "DMS compositor session";
    };
  };

  systemd.user.services.dms = {
    Unit = {
      PartOf = lib.mkForce ["dms-session.target"];
      After = lib.mkForce [];
    };
    Install.WantedBy = lib.mkForce ["dms-session.target"];
  };
}
